using MySqlConnector; using System.Collections.ObjectModel;
namespace ApotekApp;
public partial class PelangganPage:ContentPage{
 readonly ObservableCollection<P> items=new(); int editId;
 public PelangganPage(){InitializeComponent();Cv.ItemsSource=items;}
 protected override async void OnAppearing(){base.OnAppearing();await LoadAsync();}
 public async Task LoadAsync(){items.Clear();await using var c=new MySqlConnection(MauiProgram.ConnectionString);await c.OpenAsync();await using var cmd=new MySqlCommand("SELECT id,no_rm,nama,nik,jenis_kelamin,tanggal_lahir,telepon,alamat,alergi,satusehat_id FROM pelanggan WHERE aktif=1 ORDER BY nama",c);await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())items.Add(new P{Id=Convert.ToInt32(r[0]),NoRM=r[1]?.ToString()??"",Nama=r[2]?.ToString()??"",NIK=r[3]?.ToString(),JK=r[4]?.ToString(),Telepon=r[6]?.ToString(),Alamat=r[7]?.ToString(),Satusehat=r[9]?.ToString()});Apply(TxtSearch.Text);}
 void Apply(string? q){var key=q?.Trim()??"";Cv.ItemsSource=string.IsNullOrWhiteSpace(key)?items:items.Where(x=>(x.NoRM+x.Nama+x.NIK+x.Telepon).Contains(key,StringComparison.OrdinalIgnoreCase)).ToList();}
 void OnSearchChanged(object s,TextChangedEventArgs e)=>Apply(e.NewTextValue); async void OnRefreshClicked(object s,EventArgs e)=>await LoadAsync();
 void OnTambahClicked(object s,EventArgs e){editId=0;Clear();LblTitle.Text="Tambah Pasien";Modal.IsVisible=true;} void OnEditClicked(object s,EventArgs e){if((s as Button)?.CommandParameter is not P x)return;editId=x.Id;LblTitle.Text="Edit Pasien";TxtRM.Text=x.NoRM;TxtNama.Text=x.Nama;TxtNIK.Text=x.NIK;CmbJK.SelectedItem=x.JK;TxtTelepon.Text=x.Telepon;TxtAlamat.Text=x.Alamat;TxtSatusehat.Text=x.Satusehat;Modal.IsVisible=true;}
 void Clear(){TxtRM.Text="";TxtNama.Text="";TxtNIK.Text="";CmbJK.SelectedItem=null;TxtTelepon.Text="";TxtAlamat.Text="";TxtAlergi.Text="";TxtSatusehat.Text="";DtpLahir.Date=DateTime.Today;}
 void OnBatalClicked(object s,EventArgs e)=>Modal.IsVisible=false;
 async void OnSimpanClicked(object s,EventArgs e){if(string.IsNullOrWhiteSpace(TxtNama.Text)){await DisplayAlert("Validasi","Nama pasien wajib diisi.","OK");return;}await using var c=new MySqlConnection(MauiProgram.ConnectionString);await c.OpenAsync();var rm=string.IsNullOrWhiteSpace(TxtRM.Text)?await NextRM(c):TxtRM.Text.Trim();string sql=editId==0?"INSERT INTO pelanggan(no_rm,nama,nik,jenis_kelamin,tanggal_lahir,telepon,alamat,alergi,satusehat_id) VALUES(@rm,@n,@nik,@jk,@lahir,@tel,@alamat,@alergi,@ss)":"UPDATE pelanggan SET no_rm=@rm,nama=@n,nik=@nik,jenis_kelamin=@jk,tanggal_lahir=@lahir,telepon=@tel,alamat=@alamat,alergi=@alergi,satusehat_id=@ss WHERE id=@id";await using var cmd=new MySqlCommand(sql,c);cmd.Parameters.AddWithValue("@rm",rm);cmd.Parameters.AddWithValue("@n",TxtNama.Text.Trim());cmd.Parameters.AddWithValue("@nik",(object?)TxtNIK.Text??DBNull.Value);cmd.Parameters.AddWithValue("@jk",(object?)CmbJK.SelectedItem?.ToString()??DBNull.Value);cmd.Parameters.AddWithValue("@lahir",DtpLahir.Date.ToString("yyyy-MM-dd"));cmd.Parameters.AddWithValue("@tel",(object?)TxtTelepon.Text??DBNull.Value);cmd.Parameters.AddWithValue("@alamat",(object?)TxtAlamat.Text??DBNull.Value);cmd.Parameters.AddWithValue("@alergi",(object?)TxtAlergi.Text??DBNull.Value);cmd.Parameters.AddWithValue("@ss",(object?)TxtSatusehat.Text??DBNull.Value);if(editId>0)cmd.Parameters.AddWithValue("@id",editId);try{await cmd.ExecuteNonQueryAsync();Modal.IsVisible=false;await LoadAsync();}catch(Exception ex){await DisplayAlert("Gagal Menyimpan",ex.Message,"OK");}}
 static async Task<string> NextRM(MySqlConnection c){await using var cmd=new MySqlCommand("SELECT COALESCE(MAX(id),0)+1 FROM pelanggan",c);return $"RM-{Convert.ToInt32(await cmd.ExecuteScalarAsync()):D6}";}
 class P{public int Id{get;set;}public string NoRM{get;set;}="";public string Nama{get;set;}="";public string? NIK{get;set;}public string? JK{get;set;}public string? Telepon{get;set;}public string? Alamat{get;set;}public string? Satusehat{get;set;}}
}
