using MySqlConnector;
namespace ApotekApp;
public partial class SettingPage:ContentPage{
 public SettingPage(){InitializeComponent();} protected override async void OnAppearing(){base.OnAppearing();await LoadSettingsAsync();}
 public async Task LoadSettingsAsync(){try{await using var c=new MySqlConnection(MauiProgram.ConnectionString);await c.OpenAsync();await using var cmd=new MySqlCommand("SELECT nama_apotek,alamat,no_telepon,sia_sipa,pajak_ppn,organization_id,satusehat_client_id,satusehat_client_secret FROM pengaturan WHERE id=1",c);await using var r=await cmd.ExecuteReaderAsync();if(await r.ReadAsync()){EntNamaApotek.Text=r[0]?.ToString();EntAlamatApotek.Text=r[1]?.ToString();EntTeleponApotek.Text=r[2]?.ToString();EntSia.Text=r[3]?.ToString();EntPpn.Text=r[4]?.ToString();EntOrg.Text=r[5]?.ToString();EntClient.Text=r[6]?.ToString();EntSecret.Text=r[7]?.ToString();}else LoadFallback();}catch{LoadFallback();}}
 void LoadFallback(){EntNamaApotek.Text=Preferences.Get("NamaApotek","APOTEK SEHAT");EntAlamatApotek.Text=Preferences.Get("AlamatApotek","");EntTeleponApotek.Text=Preferences.Get("TeleponApotek","");EntPpn.Text="0";}
 public void LoadSettings()=>_=LoadSettingsAsync();
 async void OnSimpanSettingClicked(object s,EventArgs e){if(string.IsNullOrWhiteSpace(EntNamaApotek.Text)){await DisplayAlert("Validasi","Nama apotek wajib diisi.","OK");return;}await using var c=new MySqlConnection(MauiProgram.ConnectionString);await c.OpenAsync();await using var cmd=new MySqlCommand("INSERT INTO pengaturan(id,nama_apotek,alamat,no_telepon,sia_sipa,pajak_ppn,organization_id,satusehat_client_id,satusehat_client_secret) VALUES(1,@n,@a,@t,@sia,@ppn,@org,@cid,@secret) ON DUPLICATE KEY UPDATE nama_apotek=VALUES(nama_apotek),alamat=VALUES(alamat),no_telepon=VALUES(no_telepon),sia_sipa=VALUES(sia_sipa),pajak_ppn=VALUES(pajak_ppn),organization_id=VALUES(organization_id),satusehat_client_id=VALUES(satusehat_client_id),satusehat_client_secret=VALUES(satusehat_client_secret)",c);cmd.Parameters.AddWithValue("@n",EntNamaApotek.Text.Trim());cmd.Parameters.AddWithValue("@a",(object?)EntAlamatApotek.Text??DBNull.Value);cmd.Parameters.AddWithValue("@t",(object?)EntTeleponApotek.Text??DBNull.Value);cmd.Parameters.AddWithValue("@sia",(object?)EntSia.Text??DBNull.Value);cmd.Parameters.AddWithValue("@ppn",decimal.TryParse(EntPpn.Text,out var ppn)?ppn:0);cmd.Parameters.AddWithValue("@org",(object?)EntOrg.Text??DBNull.Value);cmd.Parameters.AddWithValue("@cid",(object?)EntClient.Text??DBNull.Value);cmd.Parameters.AddWithValue("@secret",(object?)EntSecret.Text??DBNull.Value);await cmd.ExecuteNonQueryAsync();Preferences.Set("NamaApotek",EntNamaApotek.Text.Trim());Preferences.Set("AlamatApotek",EntAlamatApotek.Text??"");Preferences.Set("TeleponApotek",EntTeleponApotek.Text??"");await DisplayAlert("Berhasil","Pengaturan apotek tersimpan.","OK");}
 async void OnBackupClicked(object s,EventArgs e){await DisplayAlert("Backup MySQL",$"Database sekarang tersimpan di MySQL/MariaDB: {DatabaseConfig.DatabaseName}.\n\nUntuk backup, gunakan menu Export di phpMyAdmin.","OK");}
}
