using MySqlConnector; using System.Collections.ObjectModel;
namespace ApotekApp;
public partial class StokPage:ContentPage{
 readonly ObservableCollection<M> items=new(); readonly List<O> obat=new(); public StokPage(){InitializeComponent();Cv.ItemsSource=items;}
 protected override async void OnAppearing(){base.OnAppearing();await LoadAsync();}
 public async Task LoadAsync(){items.Clear();obat.Clear();await using var c=new MySqlConnection(MauiProgram.ConnectionString);await c.OpenAsync();await using(var oc=new MySqlCommand("SELECT id,NamaObat FROM obats ORDER BY namaobat",c)){await using var rr=await oc.ExecuteReaderAsync();while(await rr.ReadAsync())obat.Add(new O(Convert.ToInt32(rr[0]),rr[1].ToString()??""));}CmbObat.ItemsSource=obat.Select(x=>x.Nama).ToList();await using var cmd=new MySqlCommand("SELECT m.tanggal,COALESCE(o.NamaObat,'-'),m.jenis,m.qty_masuk,m.qty_keluar,m.stok_setelah,m.referensi FROM mutasi_stok m LEFT JOIN obats o ON o.id=m.obat_id ORDER BY m.tanggal DESC LIMIT 500",c);await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync()){int masuk=Convert.ToInt32(r[3]),keluar=Convert.ToInt32(r[4]);items.Add(new M{Waktu=DateTime.TryParse(r[0]?.ToString(),out var dt)?dt.ToString("dd/MM HH:mm"):"-",Obat=r[1]?.ToString()??"-",Jenis=r[2]?.ToString()??"-",Qty=(masuk>0?"+":"-")+Math.Max(masuk,keluar),Stok=Convert.ToInt32(r[5]),Ref=r[6]?.ToString()??"-"});}Apply();}
 void Apply(){var q=TxtSearch.Text?.Trim()??"";var j=CmbJenis.SelectedItem?.ToString()??"Semua Mutasi";Cv.ItemsSource=items.Where(x=>(string.IsNullOrWhiteSpace(q)||(x.Obat+x.Ref).Contains(q,StringComparison.OrdinalIgnoreCase))&&(j=="Semua Mutasi"||x.Jenis==j)).ToList();}
 void OnSearchChanged(object s,TextChangedEventArgs e)=>Apply();void OnFilterChanged(object s,EventArgs e)=>Apply();async void OnRefreshClicked(object s,EventArgs e)=>await LoadAsync();void OnAdjustClicked(object s,EventArgs e){CmbObat.SelectedItem=null;CmbArah.SelectedIndex=0;TxtQty.Text="";TxtRef.Text="";Modal.IsVisible=true;}void OnBatalClicked(object s,EventArgs e)=>Modal.IsVisible=false;
 async void OnSimpanClicked(object s,EventArgs e){if(CmbObat.SelectedItem is not string name||!int.TryParse(TxtQty.Text,out var qty)||qty<=0){await DisplayAlert("Validasi","Pilih obat dan isi jumlah yang benar.","OK");return;}var o=obat.First(x=>x.Nama==name);var masuk=CmbArah.SelectedIndex==0?qty:0;var keluar=CmbArah.SelectedIndex==1?qty:0;await using var c=new MySqlConnection(MauiProgram.ConnectionString);await c.OpenAsync();await using var tx=c.BeginTransaction();try{await using(var u=new MySqlCommand("UPDATE obats SET Stok=Stok+@in-@out WHERE id=@id AND Stok>=@out",c,tx)){u.Parameters.AddWithValue("@in",masuk);u.Parameters.AddWithValue("@out",keluar);u.Parameters.AddWithValue("@id",o.Id);if(await u.ExecuteNonQueryAsync()!=1)throw new Exception("Stok tidak mencukupi untuk pengeluaran.");}int stok;await using(var q=new MySqlCommand("SELECT stok FROM obats WHERE id=@id",c,tx)){q.Parameters.AddWithValue("@id",o.Id);stok=Convert.ToInt32(await q.ExecuteScalarAsync());}await using(var ins=new MySqlCommand("INSERT INTO mutasi_stok(tanggal,obat_id,jenis,qty_masuk,qty_keluar,stok_setelah,referensi,user_id) VALUES(@tgl,@id,'Penyesuaian',@in,@out,@stok,@ref,@uid)",c,tx)){ins.Parameters.AddWithValue("@tgl",DateTime.Now);ins.Parameters.AddWithValue("@id",o.Id);ins.Parameters.AddWithValue("@in",masuk);ins.Parameters.AddWithValue("@out",keluar);ins.Parameters.AddWithValue("@stok",stok);ins.Parameters.AddWithValue("@ref",(object?)TxtRef.Text??DBNull.Value);ins.Parameters.AddWithValue("@uid",Preferences.Get("CurrentUserId",0));await ins.ExecuteNonQueryAsync();}tx.Commit();Modal.IsVisible=false;await LoadAsync();}catch(Exception ex){tx.Rollback();await DisplayAlert("Gagal",ex.Message,"OK");}}
 record O(int Id,string Nama);class M{public string Waktu="",Obat="",Jenis="",Qty="",Ref="";public int Stok;}
}
